--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "ADMIN" ADD PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCESS_LOG
--------------------------------------------------------

  ALTER TABLE "ACCESS_LOG" ADD PRIMARY KEY ("ACCESS_LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table BASKET
--------------------------------------------------------

  ALTER TABLE "BASKET" ADD PRIMARY KEY ("BASKET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table BASKET_PRODUCT
--------------------------------------------------------

  ALTER TABLE "BASKET_PRODUCT" ADD PRIMARY KEY ("BASKET_PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "BASKET_PRODUCT" MODIFY ("PRODUCT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BASKET_PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "BASKET_PRODUCT" MODIFY ("BASKET_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLLECTION_SLOT
--------------------------------------------------------

  ALTER TABLE "COLLECTION_SLOT" ADD PRIMARY KEY ("COLLECTION_SLOT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "COLLECTION_SLOT" MODIFY ("MAXIMUM_ORDERS" NOT NULL ENABLE);
  ALTER TABLE "COLLECTION_SLOT" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "COLLECTION_SLOT" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "COLLECTION_SLOT" MODIFY ("ADDED_BY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMER" ADD PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table DISCOUNT
--------------------------------------------------------

  ALTER TABLE "DISCOUNT" ADD PRIMARY KEY ("DISCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "INVOICE" ADD PRIMARY KEY ("INVOICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "INVOICE" MODIFY ("TOTAL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "INVOICE" MODIFY ("INVOICE_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYMENT_DETAIL
--------------------------------------------------------

  ALTER TABLE "PAYMENT_DETAIL" ADD PRIMARY KEY ("PAYMENT_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "PAYMENT_DETAIL" MODIFY ("PAYMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PAYMENT_DETAIL" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "PAYMENT_DETAIL" MODIFY ("BASKET_PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PRODUCT" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "PRODUCT" MODIFY ("MAX_ORDER" NOT NULL ENABLE);
  ALTER TABLE "PRODUCT" MODIFY ("MIN_ORDER" NOT NULL ENABLE);
  ALTER TABLE "PRODUCT" MODIFY ("STOCK_AVAILABLE" NOT NULL ENABLE);
  ALTER TABLE "PRODUCT" MODIFY ("QUANTITY_PER_ITEM" NOT NULL ENABLE);
  ALTER TABLE "PRODUCT" MODIFY ("PRODUCT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT_COMMENT
--------------------------------------------------------

  ALTER TABLE "PRODUCT_COMMENT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "PRODUCT_COMMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "PRODUCT_COMMENT" ADD PRIMARY KEY ("PRODUCT_COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_TYPE
--------------------------------------------------------

  ALTER TABLE "PRODUCT_TYPE" MODIFY ("PRODUCT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PRODUCT_TYPE" ADD PRIMARY KEY ("PRODUCT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table SHOP
--------------------------------------------------------

  ALTER TABLE "SHOP" ADD PRIMARY KEY ("SHOP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "SHOP" MODIFY ("SHOP_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOP_COMMENT
--------------------------------------------------------

  ALTER TABLE "SHOP_COMMENT" ADD PRIMARY KEY ("SHOP_COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table TRADER
--------------------------------------------------------

  ALTER TABLE "TRADER" ADD PRIMARY KEY ("TRADER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table TRADER_TYPE
--------------------------------------------------------

  ALTER TABLE "TRADER_TYPE" ADD PRIMARY KEY ("TRADER_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "TRADER_TYPE" MODIFY ("TRADER_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VALIDATION_TOKEN
--------------------------------------------------------

  ALTER TABLE "VALIDATION_TOKEN" ADD CONSTRAINT "VALIDATION_TOKEN_PK" PRIMARY KEY ("VALIDATION_TOKEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE "VALIDATION_TOKEN" MODIFY ("VALIDATION_TOKEN_ID" NOT NULL ENABLE);
  ALTER TABLE "VALIDATION_TOKEN" MODIFY ("VALIDATION_TOKEN" NOT NULL ENABLE);
  ALTER TABLE "VALIDATION_TOKEN" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "ADMIN" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCESS_LOG
--------------------------------------------------------

  ALTER TABLE "ACCESS_LOG" ADD CONSTRAINT "ACCESS_LOG_FK_TRADER" FOREIGN KEY ("TRADER_ID")
	  REFERENCES "TRADER" ("TRADER_ID") ENABLE;
  ALTER TABLE "ACCESS_LOG" ADD FOREIGN KEY ("ADMIN_ID")
	  REFERENCES "ADMIN" ("ADMIN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BASKET
--------------------------------------------------------

  ALTER TABLE "BASKET" ADD FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("CUSTOMER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BASKET_PRODUCT
--------------------------------------------------------

  ALTER TABLE "BASKET_PRODUCT" ADD FOREIGN KEY ("BASKET_ID")
	  REFERENCES "BASKET" ("BASKET_ID") ENABLE;
  ALTER TABLE "BASKET_PRODUCT" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PRODUCT" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "BASKET_PRODUCT" ADD FOREIGN KEY ("DISCOUNT_ID")
	  REFERENCES "DISCOUNT" ("DISCOUNT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COLLECTION_SLOT
--------------------------------------------------------

  ALTER TABLE "COLLECTION_SLOT" ADD FOREIGN KEY ("ADDED_BY")
	  REFERENCES "ADMIN" ("ADMIN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMER" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "INVOICE" ADD CONSTRAINT "INVOICE_FK_COLLECTION_SLOT" FOREIGN KEY ("COLLECTION_SLOT_ID")
	  REFERENCES "COLLECTION_SLOT" ("COLLECTION_SLOT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INVOICE" ADD FOREIGN KEY ("DISCOUNT_ID")
	  REFERENCES "DISCOUNT" ("DISCOUNT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT_DETAIL
--------------------------------------------------------

  ALTER TABLE "PAYMENT_DETAIL" ADD FOREIGN KEY ("BASKET_PRODUCT_ID")
	  REFERENCES "BASKET_PRODUCT" ("BASKET_PRODUCT_ID") ENABLE;
  ALTER TABLE "PAYMENT_DETAIL" ADD FOREIGN KEY ("INVOICE_ID")
	  REFERENCES "INVOICE" ("INVOICE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PRODUCT" ADD FOREIGN KEY ("PRODUCT_TYPE_ID")
	  REFERENCES "PRODUCT_TYPE" ("PRODUCT_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_COMMENT
--------------------------------------------------------

  ALTER TABLE "PRODUCT_COMMENT" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PRODUCT" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "PRODUCT_COMMENT" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
  ALTER TABLE "PRODUCT_COMMENT" ADD FOREIGN KEY ("REPLY_OF")
	  REFERENCES "PRODUCT_COMMENT" ("PRODUCT_COMMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_TYPE
--------------------------------------------------------

  ALTER TABLE "PRODUCT_TYPE" ADD FOREIGN KEY ("SHOP_ID")
	  REFERENCES "SHOP" ("SHOP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOP
--------------------------------------------------------

  ALTER TABLE "SHOP" ADD FOREIGN KEY ("TRADER_TYPE_ID")
	  REFERENCES "TRADER_TYPE" ("TRADER_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOP_COMMENT
--------------------------------------------------------

  ALTER TABLE "SHOP_COMMENT" ADD FOREIGN KEY ("SHOP_ID")
	  REFERENCES "PRODUCT" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "SHOP_COMMENT" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SHOP_COMMENT" ADD FOREIGN KEY ("REPLY_OF")
	  REFERENCES "PRODUCT_COMMENT" ("PRODUCT_COMMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRADER
--------------------------------------------------------

  ALTER TABLE "TRADER" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
  ALTER TABLE "TRADER" ADD CONSTRAINT "TRADER_FK_ADMIN" FOREIGN KEY ("PROPOSAL_ACCEPTED_BY")
	  REFERENCES "ADMIN" ("ADMIN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRADER_TYPE
--------------------------------------------------------

  ALTER TABLE "TRADER_TYPE" ADD FOREIGN KEY ("TRADER_ID")
	  REFERENCES "TRADER" ("TRADER_ID") ENABLE;
  ALTER TABLE "TRADER_TYPE" ADD CONSTRAINT "TRADER_TYPE_APPROVED_BY_FK" FOREIGN KEY ("APPROVED_BY")
	  REFERENCES "ADMIN" ("ADMIN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VALIDATION_TOKEN
--------------------------------------------------------

  ALTER TABLE "VALIDATION_TOKEN" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;