--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "ADMIN" 
   (	"ADMIN_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table ACCESS_LOG
--------------------------------------------------------

  CREATE TABLE "ACCESS_LOG" 
   (	"ACCESS_LOG_ID" NUMBER(*,0), 
	"TRADER_ID" NUMBER(*,0), 
	"ADMIN_ID" NUMBER(*,0), 
	"ACCESS_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ACTIVITY" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table BASKET
--------------------------------------------------------

  CREATE TABLE "BASKET" 
   (	"BASKET_ID" NUMBER(*,0), 
	"CUSTOMER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table BASKET_PRODUCT
--------------------------------------------------------

  CREATE TABLE "BASKET_PRODUCT" 
   (	"BASKET_PRODUCT_ID" NUMBER(*,0), 
	"BASKET_ID" NUMBER(*,0), 
	"PRODUCT_ID" NUMBER(*,0), 
	"ADDED_TO_BASKET_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"PRODUCT_PRICE" NUMBER(10,2), 
	"DISCOUNT_ID" NUMBER(*,0), 
	"PRODUCT_QUANTITY" NUMBER DEFAULT 1, 
	"TRX_COMPLETED" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table COLLECTION_SLOT
--------------------------------------------------------

  CREATE TABLE "COLLECTION_SLOT" 
   (	"COLLECTION_SLOT_ID" NUMBER(*,0), 
	"ADDED_BY" NUMBER(*,0), 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"MAXIMUM_ORDERS" NUMBER(*,0), 
	"REMAINING_ORDERS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table DISCOUNT
--------------------------------------------------------

  CREATE TABLE "DISCOUNT" 
   (	"DISCOUNT_ID" NUMBER(*,0), 
	"DISCOUNT_AMOUNT" NUMBER(3,2), 
	"DESCRIPTION" LONG
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table INVOICE
--------------------------------------------------------

  CREATE TABLE "INVOICE" 
   (	"INVOICE_ID" NUMBER(*,0), 
	"DISCOUNT_ID" NUMBER(*,0), 
	"INVOICE_TIME" TIMESTAMP (6), 
	"TOTAL_AMOUNT" NUMBER(10,2), 
	"DELIVERY_STATUS" VARCHAR2(10 BYTE), 
	"COLLECTION_SLOT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table PAYMENT_DETAIL
--------------------------------------------------------

  CREATE TABLE "PAYMENT_DETAIL" 
   (	"PAYMENT_DETAIL_ID" NUMBER(*,0), 
	"BASKET_PRODUCT_ID" NUMBER(*,0), 
	"PAYMENT_IDENTIFICATION" VARCHAR2(50 BYTE), 
	"INVOICE_ID" NUMBER(*,0), 
	"PAYMENT_TYPE" VARCHAR2(10 BYTE), 
	"PAYMENT_EMAIL" VARCHAR2(100 BYTE), 
	"TRANSACTION_TIME" TIMESTAMP (6), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"PAYMENT_AMOUNT" NUMBER(10,2), 
	"ADDRESS_STREET" VARCHAR2(50 BYTE), 
	"ADDRESS_CITY" VARCHAR2(50 BYTE), 
	"ADDRESS_STATE" VARCHAR2(50 BYTE), 
	"ADDRESS_ZIP" VARCHAR2(50 BYTE), 
	"ADDRESS_COUNTRY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "PRODUCT" 
   (	"PRODUCT_ID" NUMBER(*,0), 
	"PRODUCT_TYPE_ID" NUMBER(*,0), 
	"PRODUCT_NAME" VARCHAR2(50 BYTE), 
	"PRODUCT_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"PRODUCT_PRICE" NUMBER(10,2), 
	"QUANTITY_PER_ITEM" VARCHAR2(10 BYTE), 
	"STOCK_AVAILABLE" NUMBER, 
	"MIN_ORDER" NUMBER(*,0), 
	"MAX_ORDER" NUMBER(*,0), 
	"ALLERGY_INFORMATION" VARCHAR2(150 BYTE), 
	"PRODUCT_ADDED_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table PRODUCT_COMMENT
--------------------------------------------------------

  CREATE TABLE "PRODUCT_COMMENT" 
   (	"PRODUCT_COMMENT_ID" NUMBER(*,0), 
	"PRODUCT_ID" NUMBER(11,0), 
	"USER_ID" NUMBER(11,0), 
	"REPLY_OF" NUMBER(*,0), 
	"PRODUCT_COMMENT" VARCHAR2(1000 BYTE), 
	"RATING" NUMBER(2,1), 
	"COMMENT_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table PRODUCT_TYPE
--------------------------------------------------------

  CREATE TABLE "PRODUCT_TYPE" 
   (	"PRODUCT_TYPE_ID" NUMBER(*,0), 
	"SHOP_ID" NUMBER(*,0), 
	"PRODUCT_TYPE" VARCHAR2(50 BYTE), 
	"PRODUCT_TYPE_DESCRIPTION" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SHOP
--------------------------------------------------------

  CREATE TABLE "SHOP" 
   (	"SHOP_ID" NUMBER(*,0), 
	"TRADER_TYPE_ID" NUMBER(*,0), 
	"SHOP_NAME" VARCHAR2(100 BYTE), 
	"SHOP_DESCRIPTION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SHOP_COMMENT
--------------------------------------------------------

  CREATE TABLE "SHOP_COMMENT" 
   (	"SHOP_COMMENT_ID" NUMBER(*,0), 
	"SHOP_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"REPLY_OF" NUMBER(*,0), 
	"PRODUCT_COMMENT" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table TRADER
--------------------------------------------------------

  CREATE TABLE "TRADER" 
   (	"TRADER_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"VAT_REGISTRATION_NUMBER" VARCHAR2(100 BYTE), 
	"PROPOSAL_ACCEPTED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"PROPOSAL_ACCEPTED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table TRADER_TYPE
--------------------------------------------------------

  CREATE TABLE "TRADER_TYPE" 
   (	"TRADER_TYPE_ID" NUMBER(*,0), 
	"TRADER_ID" NUMBER(*,0), 
	"TRADER_TYPE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(150 BYTE), 
	"APPROVED" VARCHAR2(1 BYTE) DEFAULT NULL, 
	"APPROVED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"PHONE_NUMBER" VARCHAR2(50 BYTE), 
	"IS_VERIFIED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"PASSWORD" VARCHAR2(150 BYTE), 
	"USER_TYPE" VARCHAR2(10 BYTE) DEFAULT 'CUSTOMER', 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table VALIDATION_TOKEN
--------------------------------------------------------

  CREATE TABLE "VALIDATION_TOKEN" 
   (	"USER_ID" NUMBER(*,0), 
	"VALIDATION_TOKEN" VARCHAR2(250 BYTE), 
	"VALIDATION_TOKEN_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;